name: Publish MCP Server to NPM

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install & Build TypeScript SDK
        working-directory: typescript
        run: |
          npm install
          npm run build
          
      - name: Install & Build MCP Server
        working-directory: mcp
        run: |
          npm install
          npm run build
          
      - name: Publish to NPM
        working-directory: mcp
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
